name: smartdigitalpsicoapiproject
services:  
   smartdigitalpsico.webapi:
    image:  leonecr/smartdigitalpsicoapihomolog:latest
    container_name: smartdigitalpsicoapicontainer
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Production 
      ASPNETCORE_URLS: https://+:443;http://+:80
    build:
      context: .
      dockerfile: SmartDigitalPsico.WebAPI/Dockerfile 
    ports: # porta do host:porta do container    
      - "80:80"
      - "443:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - smartdigitalpsiconetwork  
networks:
  smartdigitalpsiconetwork:
    driver: bridge